language: python
dist: xenial
python:
    - "3.7"

install:
    - pip install tox-travis==0.12 tox==3.12.1

script:
    - tox

notifications:
    email:
        recipients:
            - psangkloy@argo.ai
        on_success: change
        on_failure: change
